name: easy_pedidos_flutter
description: Easy Pedidos - App de gestão de pedidos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de estado
  provider: ^6.1.1

  # Navegação
  go_router: ^13.2.0

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1

  # Utilitários
  equatable: ^2.0.5
  collection: ^1.18.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
